- name: copy payment service local to remote
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/{{ component }}.service

- name: Install python3 package
  ansible.builtin.dnf:
    name:
      - python3
      - gcc
      - python3-devel
    state: present

- name: import common node
  ansible.builtin.include_role:
    name: common

- name: Install requirements
  ansible.builtin.pip:
    requirements: /app/requirements.txt
    executable: pip3

- name: import backend script
  ansible.builtin.include_role:
    name: common
    tasks_from: backend_script.yaml