- name: copy service local to remote
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/{{ component }}.service

- name: Use role in loop
  ansible.builtin.include_role:
    name: common
    tasks_from: "{{ item }}"
  loop:
    - node.yaml
    - npm.yaml
    - mongo.yaml

- name: run backend script
  ansible.builtin.include_role:
    name: common
    tasks_from: backend_script.yaml



