- name: copy service local to remote
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/{{ component }}.service

- name: pre-req code
  ansible.builtin.include_role:
    name: common

- name: Use role in loop
  ansible.builtin.include_role:
    name: common
    tasks_from: "{{ item }}"
  loop:
    - node
    - npm
    - mongo
  loop_control:
    loop_var: item

- name: run backend script
  ansible.builtin.include_role:
    name: common
    tasks_from: backend_script.yaml



